# Generated by Django 4.2.2 on 2023-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('age', models.IntegerField(max_length=10)),
                ('standard', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=1000)),
            ],
        ),
    ]
