# Generated by Django 4.2.2 on 2023-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='standard',
            field=models.IntegerField(),
        ),
    ]
