# Generated by Django 4.2.2 on 2023-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0002_alter_student_model_age_alter_student_model_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='address',
            field=models.CharField(default='address', max_length=10000),
        ),
    ]
